### PR TITLE
Fixed Url Mapping

### PR DESCRIPTION
**Pull request by Inrmanish**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hi, i don't think this PR was intended as-is, right? Feel free to re-open, if it has a valid usecase.

**Comment by Mikescops** [comment]
i think he mentioned it in #50 but it's likely missing a part

**Comment by bobdenotter** [comment]
@Mikescops I'm not sure.. They made another confusing PR's here: 

- https://github.com/bolt/redactor/pull/29
- https://github.com/facebook/react/pull/23325
- https://github.com/microsoft/terminal/pull/12519

**Comment by Mikescops** [comment]
right, probably a bot

**Pull request closed without merging**
